### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by sgansky** [geerlingguy/pico-w-garage-door-sensor#11]
I'm not really a software guy but I've managed to get to the compile stage and get this error.

Tool Manager: Installing earlephilhower/toolchain-rp2040-earlephilhower @ 5.100300.220714
INFO Installing earlephilhower/toolchain-rp2040-earlephilhower @ 5.100300.220714
Error: Could not find the package with 'earlephilhower/toolchain-rp2040-earlephilhower @ 5.100300.220714' requirements for your system 'linux_armv7l'

I've been searching for days to see what I'm doing wrong with no luck.  I running this on a Pi400 running Buster 10

Thanks

**Comment by MrMaou** [comment]
The Pi 400 is not a supported device for this. Needs to be an ESP8266, ESP32 or RP2040, which can be seen under the platforms section on their site https://esphome.io/#platforms

**Comment by sgansky** [comment]
I did manage to get it going!  Now just trying to get the ESP to work on the iPhone.  Thanks

**Comment by maxgerhardt** [comment]
We resolved this issue of not having a toolchain for ARMv7l (i.e. people running an outdated 32-bit version of Raspbian on their Pis) per https://github.com/earlephilhower/pico-quick-toolchain/issues/22 and [this](https://github.com/maxgerhardt/platform-raspberrypi/issues/18#issuecomment-1364553964) two days after this issue was opened, as can be seen in [the compatibility matrix](https://registry.platformio.org/tools/earlephilhower/toolchain-rp2040-earlephilhower/compatibility). So I think this issue can be closed.

**Comment by geerlingguy** [comment]
Thanks!
